---

pipeline: "Nanopore Cas9 enrichment tutorial"

# define a name to describe the workflow; this will be used to name BAM files etc
study_name: "cas9_FAK76554"

# pointer to a reference sequence that reads will be mapped to
reference_genome: "http://ftp.ensembl.org/pub/release-96/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

# bed file describing the target regions 
target_regions: "RawData/repeatpanel.bed"

# fastq sequences to be mapped placed in a folder
fastq: "RawData/DoubleCut/20190502_1617_GA30000_FAK76554_5a42db91/fastq_pass"
#fastq: "RawData/DoubleCut/20190502_1617_GA30000_FAK76554_5a42db91/FAK76554_9b52beb8b4f9ec458eb28c28b35822acaff84952.fastq"

# some genome geometry values
# gstride is the bin size for summarising depth of coverage across the reference_genome
gstride: 100
# target_proximity is the distance up- and down-stream of ontarget BED for defining target proximal mapping
target_proximity: 25000
# a threshold for defining off-target mapping; this is ($level$ * mean background) expression
offtarget_level: 20

tutorialText: TRUE
