channels:
  - bioconda
  - conda-forge
  - r
  - sagrudd
dependencies:
  - snakemake-minimal
  - python
  - samtools
  - minimap2
  - seqtk
  - r
  - rstudio
  - graphviz
  - imagemagick
  - ont_tutorial_cas9
  - pandas
  